"""
LLM-powered policy reasoning agent.

The scoring and recommendation engines are deterministic - they produce the
same output for the same inventory every time, which is exactly what you
want for the underlying analysis. But a human decision-maker also needs the
analysis explained in prose: why this asset before that one, what the
sector-specific blockers mean in practice, and what a sensible first quarter
of work looks like.

This module asks Claude to reason over the already-processed inventory
(not the raw JSON - the deterministic pipeline has already done the
classification, scoring, and recommendation work) and produce a structured,
chain-of-thought migration briefing. Keeping the deterministic pipeline and
the LLM layer separate means the numbers a compliance team relies on are
never generated by the model - only the narrative around them is.
"""

from __future__ import annotations

import json
from dataclasses import asdict
from typing import Any

from .models import Inventory

SYSTEM_PROMPT = """\
You are a post-quantum cryptography migration advisor. You will be given a \
cryptographic asset inventory that has already been classified, scored, and \
matched to NIST FIPS replacements by a deterministic analysis pipeline - do \
not recompute or second-guess those numbers. Your job is to reason about \
sequencing and practical trade-offs across the whole portfolio of assets.

Think step by step through the following before answering:
1. Which assets represent the genuine near-term risk, considering both the \
urgency score and any sector-specific blockers - a high score with an \
unresolved protocol-redesign blocker is not "ready to migrate" in the same \
way a high score with no blockers is.
2. Which assets share a migration dependency or a natural batching \
opportunity (e.g. the same gateway, the same firmware release train).
3. What a realistic first-quarter migration plan looks like given the \
above, not just a re-sorted list by urgency score.

Respond with a single JSON object and nothing else - no markdown fences, no \
preamble - with exactly these keys:
{
  "analysis": "<string: your step-by-step reasoning>",
  "recommendations": [
    {"asset_id": "<string>", "priority_rank": <integer>, "rationale": "<string>"}
  ]
}
"""

_MODEL = "claude-sonnet-4-6"


def _inventory_to_context(inventory: Inventory) -> str:
    """Serialise the already-processed inventory into the JSON the agent reasons over."""
    payload: dict[str, Any] = {
        "system_name": inventory.system_name,
        "crqc_horizon_years": inventory.crqc_horizon_years,
        "assets": [
            {
                **{k: v for k, v in asdict(asset).items() if k not in ("vulnerability",)},
                "vulnerability": asset.vulnerability.value if asset.vulnerability else None,
            }
            for asset in inventory.assets
        ],
    }
    return json.dumps(payload, indent=2)


def build_request(inventory: Inventory) -> dict[str, Any]:
    """
    Build the Messages API request body for a policy briefing over this
    inventory. Split out from generate_policy_briefing() so the request can
    be inspected or unit tested without making a network call.
    """
    return {
        "model": _MODEL,
        "max_tokens": 2000,
        "system": SYSTEM_PROMPT,
        "messages": [
            {"role": "user", "content": _inventory_to_context(inventory)},
        ],
    }


def parse_response(raw_text: str) -> dict[str, Any]:
    """
    Parse the agent's JSON response, tolerating an accidental markdown fence
    since models sometimes add one despite being told not to.
    """
    cleaned = raw_text.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.strip("`")
        if cleaned.startswith("json"):
            cleaned = cleaned[4:]
        cleaned = cleaned.strip()

    return json.loads(cleaned)


def generate_policy_briefing(inventory: Inventory, client: Any) -> dict[str, Any]:
    """
    Call the Anthropic Messages API to produce a policy briefing.

    `client` is an already-constructed `anthropic.Anthropic()` instance - it
    is passed in rather than created here so tests can substitute a fake
    client without touching the network or requiring an API key.
    """
    request = build_request(inventory)
    response = client.messages.create(**request)
    raw_text = "".join(block.text for block in response.content if block.type == "text")
    return parse_response(raw_text)
